### ISSUE TITLE
Change of title in the Quiz page

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-programming-responsive-iiith#2]
When I try to open the quiz page in expression evaluation experiment, found that the quiz page is opening in Numerical Approximation experiment. Even no content is updated in this page.

**Comment by khushpreet-kaur** [comment]
This issue has been fixed!

**Comment by khushpreet-kaur** [comment]
@BSravanthi  Please check and close  the issue!

**Comment by BSravanthi** [comment]
@khushpreet-kaur  The title of the page is still showing as Numerical Approximation.

**Comment by khushpreet-kaur** [comment]
@BSravanthi I have sent request for hosting! Once systems team re-host this lab, changes will reflect.
